# Exercise 3: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [4]:
#3.2: create a random 10x10 array named A
randomMatrix = np.random.rand(10,10)
randomMatrix

array([[0.22771929, 0.18537704, 0.34311358, 0.4951386 , 0.45013757,
        0.61026016, 0.1634036 , 0.7471036 , 0.57338526, 0.92477129],
       [0.77120671, 0.42581921, 0.67671081, 0.09827399, 0.04261969,
        0.18596219, 0.66784219, 0.16465712, 0.01039675, 0.34619671],
       [0.86433834, 0.02021149, 0.19367165, 0.31166911, 0.68689989,
        0.5468699 , 0.38226661, 0.96888936, 0.38965593, 0.43501647],
       [0.43027806, 0.03065168, 0.40353224, 0.19814305, 0.95181898,
        0.68210193, 0.6214067 , 0.07368305, 0.67944665, 0.75169329],
       [0.23531814, 0.12841532, 0.44309473, 0.87633168, 0.00620517,
        0.29264617, 0.4088304 , 0.9376937 , 0.22696686, 0.74277756],
       [0.97534409, 0.9737423 , 0.16715542, 0.4791337 , 0.32789996,
        0.80078588, 0.17216229, 0.96192811, 0.9696594 , 0.48418071],
       [0.4235856 , 0.82159151, 0.87777492, 0.84088882, 0.79817425,
        0.8480336 , 0.08523846, 0.60940282, 0.5197304 , 0.1103954 ],
       [0.88262676, 0.21232996, 0.1887262

In [11]:
#3.3: return only the odd rows of A
oddRows = randomMatrix[::2]
oddRows

array([[0.22771929, 0.18537704, 0.34311358, 0.4951386 , 0.45013757,
        0.61026016, 0.1634036 , 0.7471036 , 0.57338526, 0.92477129],
       [0.86433834, 0.02021149, 0.19367165, 0.31166911, 0.68689989,
        0.5468699 , 0.38226661, 0.96888936, 0.38965593, 0.43501647],
       [0.23531814, 0.12841532, 0.44309473, 0.87633168, 0.00620517,
        0.29264617, 0.4088304 , 0.9376937 , 0.22696686, 0.74277756],
       [0.4235856 , 0.82159151, 0.87777492, 0.84088882, 0.79817425,
        0.8480336 , 0.08523846, 0.60940282, 0.5197304 , 0.1103954 ],
       [0.75849183, 0.01767437, 0.70568728, 0.53334252, 0.73862495,
        0.77427645, 0.88017954, 0.96065769, 0.18690966, 0.82492859]])

In [17]:
#3.4: perform a matrix multiplication of A with it's transposed
multiMatrix = np.dot(randomMatrix, np.transpose(randomMatrix))
multiMatrix
#multiMatrix2 = np.matrix(randomMatrix) * np.matrix(randomMatrix.T)
#multiMatrix2

array([[2.79298832, 1.22633158, 2.47631459, 2.42625757, 2.42911019,
        3.08402955, 2.71241673, 2.41948809, 3.21877877, 2.81247044],
       [1.22633158, 1.87316088, 1.53733195, 1.49927557, 1.36375282,
        1.94099186, 1.74576929, 1.8491581 , 2.33143707, 1.69544801],
       [2.47631459, 1.53733195, 3.0789792 , 2.43994167, 2.20559519,
        3.29384658, 2.70040348, 3.06115348, 3.58856094, 2.48852462],
       [2.42625757, 1.49927557, 2.43994167, 3.17766613, 1.69884601,
        2.67087244, 2.60041524, 2.9461075 , 3.31334463, 2.72579244],
       [2.42911019, 1.36375282, 2.20559519, 1.69884601, 2.77147977,
        2.63698513, 2.39038593, 2.25897318, 3.1078077 , 2.63638134],
       [3.08402955, 1.94099186, 3.29384658, 2.67087244, 2.63698513,
        5.03537244, 3.8618871 , 3.57955713, 3.64899796, 3.07618681],
       [2.71241673, 1.74576929, 2.70040348, 2.60041524, 2.39038593,
        3.8618871 , 4.34920753, 3.27399407, 3.49855116, 3.2227863 ],
       [2.41948809, 1.8491581 , 3.0611534

In [25]:
#3.5: compute the matrix inverse of A
inverseMatrix = np.matrix(randomMatrix)* np.linalg.inv(randomMatrix)
inverseMatrix
#inverseMatrix2 = np.matrix(randomMatrix)* np.matrix(randomMatrix).I
#inverseMatrix2

matrix([[ 1.00000000e+00, -5.32907052e-15,  3.55271368e-15,
          0.00000000e+00,  7.10542736e-15,  0.00000000e+00,
          4.44089210e-16, -7.10542736e-15, -2.22044605e-15,
          4.44089210e-16],
        [-7.10542736e-15,  1.00000000e+00, -4.44089210e-16,
         -5.32907052e-15, -5.32907052e-15,  3.55271368e-15,
         -4.44089210e-16, -3.55271368e-15, -2.44249065e-15,
          5.55111512e-17],
        [ 1.06581410e-14,  1.77635684e-15,  1.00000000e+00,
         -5.32907052e-15, -2.84217094e-14, -8.88178420e-15,
         -8.88178420e-16,  5.32907052e-15, -6.66133815e-16,
         -1.11022302e-16],
        [ 0.00000000e+00, -1.77635684e-15,  1.77635684e-15,
          1.00000000e+00, -7.10542736e-15, -5.32907052e-15,
          0.00000000e+00,  1.77635684e-15, -2.22044605e-15,
          1.11022302e-16],
        [-2.13162821e-14, -8.88178420e-15,  7.99360578e-15,
          2.84217094e-14,  1.00000000e+00,  3.55271368e-15,
          1.33226763e-15, -1.95399252e-14, -2.664535

In [33]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

array([[0.22771929, 0.18537704, 0.34311358, 0.4951386 , 0.45013757,
        0.61026016, 0.1634036 , 0.7471036 , 0.57338526, 0.92477129],
       [0.77120671, 0.42581921, 0.67671081, 0.09827399, 0.04261969,
        0.18596219, 0.66784219, 0.16465712, 0.01039675, 0.34619671],
       [0.86433834, 0.02021149, 0.19367165, 0.31166911, 0.68689989,
        0.5468699 , 0.38226661, 0.96888936, 0.38965593, 0.43501647],
       [0.43027806, 0.03065168, 0.40353224, 0.19814305, 0.95181898,
        0.68210193, 0.6214067 , 0.07368305, 0.67944665, 0.75169329],
       [0.23531814, 0.12841532, 0.44309473, 0.87633168, 0.00620517,
        0.29264617, 0.4088304 , 0.9376937 , 0.22696686, 0.74277756],
       [0.97534409, 0.9737423 , 0.16715542, 0.4791337 , 0.32789996,
        0.80078588, 0.17216229, 0.96192811, 0.9696594 , 0.48418071],
       [0.4235856 , 0.82159151, 0.87777492, 0.84088882, 0.79817425,
        0.8480336 , 0.08523846, 0.60940282, 0.5197304 , 0.1103954 ],
       [0.88262676, 0.21232996, 0.1887262

In [36]:
condition = (randomMatrix >  0.5) 
indices= np.where(condition)
dividedMatrix = randomMatrix[indices] / 2
dividedMatrix

array([[0.22771929, 0.18537704, 0.34311358, 0.4951386 , 0.45013757,
        0.61026016, 0.1634036 , 0.7471036 , 0.57338526, 0.92477129],
       [0.77120671, 0.42581921, 0.67671081, 0.09827399, 0.04261969,
        0.18596219, 0.66784219, 0.16465712, 0.01039675, 0.34619671],
       [0.86433834, 0.02021149, 0.19367165, 0.31166911, 0.68689989,
        0.5468699 , 0.38226661, 0.96888936, 0.38965593, 0.43501647],
       [0.43027806, 0.03065168, 0.40353224, 0.19814305, 0.95181898,
        0.68210193, 0.6214067 , 0.07368305, 0.67944665, 0.75169329],
       [0.23531814, 0.12841532, 0.44309473, 0.87633168, 0.00620517,
        0.29264617, 0.4088304 , 0.9376937 , 0.22696686, 0.74277756],
       [0.97534409, 0.9737423 , 0.16715542, 0.4791337 , 0.32789996,
        0.80078588, 0.17216229, 0.96192811, 0.9696594 , 0.48418071],
       [0.4235856 , 0.82159151, 0.87777492, 0.84088882, 0.79817425,
        0.8480336 , 0.08523846, 0.60940282, 0.5197304 , 0.1103954 ],
       [0.88262676, 0.21232996, 0.1887262